name: "monoholic"
title: "monoholic"
email: hammond@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Systems architect and low-level enthusiast. Focused on distributed systems, kernel optimization, and minimalist interface design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: "stiermid"

remote_theme: stiermid/monoholic

# Build settings
markdown: kramdown
remote_theme: stiermid/monoholic

theme_config:
  back: ".."
  date_format: "%Y%m%d"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
