name: "monoholic"
title: "monoholic"
author: Agil Mammadov
email: mammadovagil@tutamail.com
description: >
  Minimal monochrome dark jekyll theme🧪
baseurl: "/monoholic" # the subpath of your site, e.g. /blog
url: "https://stiermid.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: "stiermid"

# Build settings
markdown: kramdown
remote_theme: stiermid/monoholic

theme_config:
  back: ".."
  date_format: "%Y%m%d"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
